@Library(['srePipeline@banzai']) _

def pipelinesettings = [
  deploy: [
    [name: "banzaicloud/cluster-registry-controller"]
  ],
  tagversion: "${env.BUILD_ID}",
  banzaiEcrRegistry: "033498657557.dkr.ecr.us-east-2.amazonaws.com/",
  chart: "deploy/charts",

  customContainersProject: "banzaicloud",
  customContainersCreds: "banzai_botuser_containers_cisco_com",

  // Knobs to turn on pipeline stages
  prepare: 1,
  unittest: 1,
  build: 1,
  publishHelm: 1,
  useMultipleHelm: 1,
  helmS3Private: 1,
  publishContainer: 1,
  ciscoContainer: 1,
  artifactory: 1,
  ecr: 1,
  publishGoModule: 1,

  dockerHub: 0,
  pushPublicRegistryOnTag: 0,
  preDeployE2E: 0,
  deployHelm: 0,
  sonarQube: 1,

  corona: [                                     // Corona paramters
    releaseID: "77425",                         // Corona Release ID
    productID: "7147",                          // Corona Project ID
    csdlID: "167358",                            // Corona CSDL ID
    securityContact: "banzai-backyards@cisco.com",      // Corona Security Contact
    engineeringContact: "banzai-backyards@cisco.com",   // Corona Engineering Contact
    imageAdmins: "turip,zsltvrg",           // Corona Image Admins
  ],
  blackduck: [
    email: "banzai-backyards@cisco.com",
  ],
]

srePipeline( pipelinesettings )

